version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ../db:/var/lib/mysql
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - SERVICE_TAGS=prod
      - SERVICE_NAME=nodeappservice
    networks:
      - internalnet
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","--password=$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:1.0
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ../upload_files:/usr/code/uploads
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - SERVICE_TAGS=prod
      - SERVICE_NAME=nodeappservice
      - SERVER_PORT=$NODE_DOCKER_PORT
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge